steps:
 - Checkout
# - Validate HTML
# - Validate CSS
# - Update Last Modified Date
# - Deploy
# - CloudFront Invalidation

Checkout:
  uses: actions/checkout@v7 

#Validate HTML:

#Validate CSS:

#Update Last Modified Date:

#Deploy:

#CloudFront Invalidation: