name: Portfolio Update

on:
  repository_dispatch:
    types: [project-update]

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Test dispatch
        run: echo "Portfolio update triggered"